#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# LeadDesk keeps secrets in .env.local, not .env: Next reads it natively and
# db/env.ts makes the CLI scripts read it too.
ENV_FILE=".env.local"

banner "LeadDesk setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the basics"
say "Making sure this machine can run the app before we ask you for anything."

if [[ ! -f package.json ]] || ! grep -q '"name": "leaddesk"' package.json; then
  warn "This does not look like the LeadDesk repo."
  note "cd into the repo root (the folder with package.json) and re-run:"
  note "  ./scripts/setup.sh"
  exit 1
fi
say "✓ in the LeadDesk repo"

if ! command -v node >/dev/null 2>&1; then
  warn "Node is not installed."
  note "Install Node 20 or newer from https://nodejs.org, then re-run this script."
  exit 1
fi
NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
if (( NODE_MAJOR < 20 )); then
  warn "Node $(node -v) is too old. Next.js 16 needs Node 20 or newer."
  note "Upgrade from https://nodejs.org, then re-run this script."
  exit 1
fi
say "✓ node $(node -v)"

if [[ ! -d node_modules ]]; then
  say "Installing dependencies, this takes a minute..."
  npm install
fi
say "✓ dependencies installed"
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: your database connection string"
say "This is the address and password of your database. The app reads every"
say "lead through it."
printf '\n'
open_url "https://console.neon.tech"
step "Pick your project."
step "Click the 'Connect' button on the project dashboard."
step "Click 'Copy snippet'."
printf '\n'
note "'Copy snippet' copies the real password. The dots you see on screen are"
note "just masking, so do not try to retype them."
note "The value starts with postgresql:// and ends after the database name."
printf '\n'

# Bounded, not `while true`: the library's read swallows EOF, so an unbounded
# loop would spin forever if stdin closes rather than stopping with a message.
ATTEMPTS=0
while true; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 4 )); then
    warn "Giving up after 4 tries. Nothing was saved."
    note "Re-run ./scripts/setup.sh when you have the connection string to hand."
    exit 1
  fi
  ask_secret DATABASE_URL "Paste the connection string:"
  if [[ -z "$DATABASE_URL" ]]; then
    warn "Nothing pasted. Try again, or press Ctrl-C to stop and come back later."
    continue
  fi
  if [[ "$DATABASE_URL" != postgres://* && "$DATABASE_URL" != postgresql://* ]]; then
    warn "That does not start with postgresql:// so it is probably not the string."
    note "Make sure you clicked 'Copy snippet' and not 'Connection parameters'."
    continue
  fi
  if [[ "$DATABASE_URL" == *"***"* ]]; then
    warn "That still contains the masking dots, so the password is missing."
    note "Use the 'Copy snippet' button rather than selecting the text by hand."
    continue
  fi
  break
done
write_env DATABASE_URL "$DATABASE_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon: pooled or direct?"
say "Neon serves two versions of the same database. Migrations misbehave through"
say "the pooled one, so we check which you have."
printf '\n'

if [[ "$DATABASE_URL" == *"-pooler."* ]]; then
  DIRECT_URL="${DATABASE_URL/-pooler./.}"
  warn "Yours is the POOLED string (its host contains '-pooler')."
  say "That is right for the app, but schema changes can hang through it, so"
  say "migrations need the direct one. It is the same string without '-pooler'."
  printf '\n'
  if confirm "Work out the direct string automatically and save it?"; then
    write_env DATABASE_URL_UNPOOLED "$DIRECT_URL"
  else
    say "No problem. In the same Connect modal, switch 'Connection pooling' off"
    say "and copy again."
    ask_secret DATABASE_URL_UNPOOLED "Paste the direct connection string:"
    if [[ -n "$DATABASE_URL_UNPOOLED" ]]; then
      write_env DATABASE_URL_UNPOOLED "$DATABASE_URL_UNPOOLED"
    else
      SKIPPED+=("DATABASE_URL_UNPOOLED (migrations will warn but still try)")
      warn "Left blank. Migrations will warn and use the pooled string."
    fi
  fi
else
  say "✓ Yours is the direct string, with no pooler in the host."
  say "Nothing more to do here: it works for both the app and migrations."
  write_env DATABASE_URL_UNPOOLED ""
fi
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Your passcode"
say "You invent this one. It is the only thing between the internet and your"
say "lead list, and you will thumb it in on a phone."
printf '\n'
note "There is no username, no signup and no reset link. Forget it and you edit"
note "this file to set a new one. Digits are fine. Longer beats clever."
printf '\n'

ATTEMPTS=0
while true; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 4 )); then
    warn "Giving up after 4 tries. Your database details were saved already."
    note "Re-run ./scripts/setup.sh to finish; it remembers what you entered."
    exit 1
  fi
  ask_secret APP_PASSCODE "Choose your passcode:"
  if [[ -z "$APP_PASSCODE" ]]; then
    warn "Empty passcode would let anyone in. Pick something."
    continue
  fi
  if (( ${#APP_PASSCODE} < 4 )); then
    warn "That is under 4 characters, which is guessable in seconds."
    confirm "Use it anyway?" && break
    continue
  fi
  break
done
write_env APP_PASSCODE "$APP_PASSCODE"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Session secret"
say "Random bytes that sign your login cookie so nobody can forge it."
say "You never type this one, so this script generates it here on your machine."
printf '\n'
SESSION_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
write_env SESSION_SECRET "$SESSION_SECRET"
note "Generated locally and never printed. Changing it later just signs you out;"
note "it does not touch your data."
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Create the tables and add the sample leads"
say "This creates the tables in your Neon database and adds 8 example leads so"
say "the app has something to show on the first run."
printf '\n'
note "Safe to re-run: seeding leaves any leads you already have alone."
printf '\n'

if ! confirm "Run it now against your Neon database?"; then
  SKIPPED+=("npm run db:migrate && npm run db:seed")
  warn "Skipped. Run those two commands yourself when ready."
else
  say "Creating tables..."
  if ! npm run db:migrate; then
    printf '\n'
    warn "Migration failed. The usual causes:"
    note "  - the connection string is wrong or the password was truncated"
    note "  - the Neon project is paused (open the console once to wake it)"
    note "Fix it, then re-run this script: your answers are remembered."
    exit 1
  fi

  say "Adding sample leads..."
  if ! npm run db:seed; then
    warn "Seeding failed, though the tables were created."
    note "Re-run this script to try the seed again."
    exit 1
  fi

  printf '\n'
  say "Checking what actually landed in the database..."
  node -e "
    require('dotenv').config({ path: ['.env.local', '.env'], quiet: true });
    const { Pool } = require('pg');
    const pool = new Pool({ connectionString: process.env.DATABASE_URL });
    pool.query('select stage, count(*)::int as n from leads group by 1 order by 2 desc')
      .then((r) => {
        const total = r.rows.reduce((sum, row) => sum + row.n, 0);
        console.log('  ' + total + ' leads across ' + r.rows.length + ' stages:');
        for (const row of r.rows) console.log('    ' + row.stage + ': ' + row.n);
        return pool.end();
      })
      .catch((e) => { console.error('  could not read back: ' + e.message); process.exit(0); });
  " || true
fi

finish

printf '  %sStart the app:%s\n' "$BOLD" "$RESET"
printf '    npm run dev\n\n'
printf '  Then open %shttp://localhost:3000%s and enter your passcode.\n\n' "$BLUE" "$RESET"
printf '  %sOn your phone:%s open the same address over your network, or deploy to\n' "$BOLD" "$RESET"
printf '  Vercel and add it to the home screen so it opens full-screen.\n\n'
